# Generated by Django 3.2.16 on 2023-01-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CartPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='status',
            field=models.CharField(choices=[('unpaid', 'UnPaid'), ('paid', 'Paid')], default='created', max_length=20),
        ),
    ]
