# Generated by Django 3.2.16 on 2022-11-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.CharField(choices=[('clinet', 'client'), ('coach', 'coach')], max_length=100)),
            ],
        ),
    ]
