# Generated by Django 3.2.16 on 2023-01-22 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='user',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='credit',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
