# Generated by Django 3.2.16 on 2022-12-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopStore', '0002_category_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='products', to='ShopStore.Category'),
        ),
        migrations.RemoveField(
            model_name='category',
            name='product',
        ),
        migrations.AddField(
            model_name='category',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='categories', to='ShopStore.Product'),
        ),
    ]
