# Generated by Django 3.2.16 on 2022-12-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopStore', '0003_auto_20221209_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='products', to='ShopStore.Category'),
        ),
    ]
