# Generated by Django 3.2.16 on 2023-01-22 21:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_auto_20230122_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=250)),
                ('course_code', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('rate', models.IntegerField()),
                ('data_added', models.DateTimeField()),
                ('existence', models.BooleanField()),
                ('duration', models.IntegerField()),
                ('min_students', models.IntegerField(blank=True, default=1)),
                ('max_students', models.IntegerField()),
                ('categories', models.ManyToManyField(related_name='courses', to='class.Category')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coursess', to='accounts.customuser')),
                ('students', models.ManyToManyField(blank=True, related_name='course', to='accounts.CustomUser')),
            ],
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submited_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Question', models.TextField(blank=True, default='', null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice', to='class.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice', to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submited_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('answer', models.TextField(blank=True, default='', null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='class.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='class.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='accounts.customuser')),
            ],
        ),
    ]
