# Generated by Django 3.2.16 on 2023-01-22 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230122_2311'),
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachtext',
            name='add_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Coach', to='accounts.customuser'),
        ),
        migrations.AddField(
            model_name='coachtext',
            name='subject',
            field=models.CharField(default='subject', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coachtext',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
