# Generated by Django 4.1.3 on 2022-12-16 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachtext',
            name='add_by',
        ),
        migrations.RemoveField(
            model_name='coachtext',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='coachtext',
            name='text',
        ),
    ]
