# Generated by Django 3.2.16 on 2022-12-29 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopStore', '0002_product_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
