# Generated by Django 4.1.3 on 2022-12-08 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('product_code', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('describtion', models.TextField()),
                ('slug', models.SlugField(max_length=250)),
                ('data_added', models.DateTimeField()),
                ('num_stars', models.IntegerField()),
                ('existence', models.BooleanField()),
                ('num_existence_here', models.IntegerField()),
                ('Unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manufacturer', models.CharField(max_length=250)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('review', models.TextField()),
                ('color', models.CharField(max_length=250)),
                ('images', models.ImageField(default='Images/None/No-img.jpg', upload_to='Images/')),
                ('add_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
            ],
        ),
    ]
