# Generated by Django 3.2.16 on 2022-11-15 17:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('alt', models.TextField(null=True)),
                ('images', models.ImageField(default='post/default.jpg', upload_to=shop.models.product_directory_path)),
                ('slug', models.SlugField(max_length=250, unique_for_date='created')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('active', 'active'), ('deactivated', 'deactivated')], default='active', max_length=11)),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='shop.product')),
            ],
        ),
    ]
