# Generated by Django 4.1.3 on 2022-12-16 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='num_existence_here',
            new_name='num_existence_now',
        ),
    ]
