# Generated by Django 4.1.3 on 2023-01-18 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=250)),
                ('course_code', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('rate', models.IntegerField()),
                ('data_added', models.DateTimeField()),
                ('existence', models.BooleanField()),
                ('duration', models.IntegerField()),
                ('min_students', models.IntegerField(blank=True, default=1)),
                ('max_students', models.IntegerField()),
                ('categories', models.ManyToManyField(related_name='courses', to='courses.category')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coursess', to='accounts.customuser')),
                ('students', models.ManyToManyField(blank=True, null=True, related_name='courses', to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='accounts.customuser')),
            ],
        ),
    ]
