# Generated by Django 3.2.16 on 2022-11-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('product_code', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('describtion', models.TextField()),
                ('slug', models.SlugField(max_length=250)),
                ('data_added', models.DateTimeField()),
                ('num_stars', models.IntegerField()),
                ('existence', models.BooleanField()),
                ('Unit_price', models.DecimalField(decimal_places=10, max_digits=10)),
                ('manufacturer', models.CharField(max_length=250)),
                ('discount', models.DecimalField(decimal_places=10, max_digits=10)),
                ('review', models.TextField()),
            ],
        ),
    ]
